micronaut:
  application:
    name: key-manager-rest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    key:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 5

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS