micronaut:
  application:
    name: key-manager-rest
  http:
    client:
      read-timeout: ${READ_TIMEOUT:120s}

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    key:
      address: ${GRPC_ADDRESS:`localhost:50051`}
      plaintext: true
      max-retry-attempts: 5

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}